### ISSUE TITLE
Blocked by antivirus and browser

### ISSUE THREAD

**Issue by Incrementis** [InfinityTools/WeiduInstallTool#2]
I am refering to the issue reported here:
https://www.gibberlings3.net/forums/topic/37272-weidu-install-tool-call-for-beta-testing-translations-and-proofreading/?do=findComment&comment=328966

**As evidence see screenshots:**
![2023-10-20 22_05_13-Letzte Downloads](https://github.com/InfinityTools/WeiduInstallTool/assets/17119474/7efdb0b5-213a-4e59-a403-c0b8db4a492b)
![2023-10-20 22_01_30-NortonLifeLock-Warnmeldung](https://github.com/InfinityTools/WeiduInstallTool/assets/17119474/56f22785-94d2-474a-aaf0-01aca8e7519d)

**Browser is:**
Version 118.0.5993.89 (Offizieller Build) (64-Bit); Google Chrome

The language is in German, but as far as I assume you know the German language(all the tools from you I use have German version included).

**Comment by Argent77** [comment]
Thanks for the report.

Did the security message show a link where you can report incorrectly detected files? Otherwise, this is a link to the form for reporting files to Norton: https://submit.norton.com/

It requires some information about the used av products, otherwise I would do it myself.

Some information about the file itself: It is created by the `jpackage` command from the [Temurin JDK 21](https://adoptium.net/temurin/releases/?package=jdk&os=windows&version=21) for Windows, in case it is requested.

**Comment by Incrementis** [comment]
A submission is done:

**Submission ID:**
8e232a8b-af7f-4f57-9f57-496b1dbce21e
**Submission type:**
False positive
**Submission status:**
We have received your submission and queued it for processing
**Submission details:**
Received
**Updated:**
Sat, 21 Oct 2023 05:41:39 GMT

**Comment by Argent77** [comment]
Thank you!
